// Generated by `bun run regions` — do not edit.
// Produce is defined in data/regions/, including hand-authored entries.
export default {
  id: 'ny',
  name: 'New York State',
  schemaVersion: 1,
  items: [
    {
      name: 'Blueberries',
      color: '#5b7294',
      generated: false,
      default: true,
      spans: [
        { level: 'available', from: 28, to: 29 }, // Jul 16 – Jul 29
        { level: 'peak', from: 30, to: 33 }, // Jul 30 – Aug 26
        { level: 'available', from: 34, to: 35 }, // Aug 27 – Sep 9
      ],
      sources: [
        {
          credit: 'Cornell Cooperative Extension, Tompkins County',
          url: 'https://ccetompkins.org/agriculture/buy-local/u-pick-blueberry-farms',
        },
      ],
    },
  ],
};
