// Generated by `bun run regions` — do not edit.
// Produce is defined in data/regions/, including hand-authored entries.
export default {
  id: 'sfbay',
  name: 'San Francisco Bay Area',
  schemaVersion: 1,
  items: [
    {
      name: 'Cherries',
      color: '#693038',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 19, to: 19 }, // May 7 – May 13
        { level: 'peak', from: 20, to: 22 }, // May 14 – Jun 3
        { level: 'uncertain', from: 23, to: 23 }, // Jun 4 – Jun 10
        { level: 'available', from: 24, to: 24 }, // Jun 11 – Jun 17
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Blueberries',
      color: '#5b7294',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 19, to: 20 }, // May 7 – May 20
        { level: 'peak', from: 21, to: 24 }, // May 21 – Jun 17
        { level: 'available', from: 25, to: 26 }, // Jun 18 – Jul 1
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Apricots',
      color: '#cea15e',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 21, to: 21 }, // May 21 – May 27
        { level: 'peak', from: 22, to: 24 }, // May 28 – Jun 17
        { level: 'uncertain', from: 25, to: 25 }, // Jun 18 – Jun 24
        { level: 'available', from: 26, to: 26 }, // Jun 25 – Jul 1
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Raspberries',
      color: '#ad5869',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 21, to: 23 }, // May 21 – Jun 10
        { level: 'peak', from: 24, to: 29 }, // Jun 11 – Jul 22
        { level: 'uncertain', from: 30, to: 33 }, // Jul 23 – Aug 19
        { level: 'peak', from: 34, to: 35 }, // Aug 20 – Sep 2
        { level: 'available', from: 36, to: 42 }, // Sep 3 – Oct 21
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Tomatoes',
      color: '#b2584e',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 25, to: 25 }, // Jun 18 – Jun 24
        { level: 'peak', from: 26, to: 30 }, // Jun 25 – Jul 29
        { level: 'uncertain', from: 31, to: 31 }, // Jul 30 – Aug 5
        { level: 'available', from: 32, to: 33 }, // Aug 6 – Aug 19
        { level: 'uncertain', from: 34, to: 34 }, // Aug 20 – Aug 26
        { level: 'peak', from: 35, to: 37 }, // Aug 27 – Sep 16
        { level: 'available', from: 38, to: 40 }, // Sep 17 – Oct 7
        { level: 'uncertain', from: 41, to: 42 }, // Oct 8 – Oct 21
        { level: 'available', from: 43, to: 43 }, // Oct 22 – Oct 28
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Strawberries',
      color: '#b7636e',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 17, to: 20 }, // Apr 23 – May 20
        { level: 'uncertain', from: 21, to: 21 }, // May 21 – May 27
        { level: 'peak', from: 22, to: 36 }, // May 28 – Sep 9
        { level: 'available', from: 37, to: 42 }, // Sep 10 – Oct 21
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Nectarines',
      color: '#c77d5b',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 21, to: 23 }, // May 21 – Jun 10
        { level: 'peak', from: 24, to: 34 }, // Jun 11 – Aug 26
        { level: 'available', from: 35, to: 37 }, // Aug 27 – Sep 16
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Plums',
      color: '#7e4b5e',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 23, to: 26 }, // Jun 4 – Jul 1
        { level: 'peak', from: 27, to: 31 }, // Jul 2 – Aug 5
        { level: 'uncertain', from: 32, to: 33 }, // Aug 6 – Aug 19
        { level: 'available', from: 34, to: 41 }, // Aug 20 – Oct 14
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Watermelons',
      color: '#c77580',
      generated: true,
      default: false,
      spans: [
        { level: 'available', from: 25, to: 26 }, // Jun 18 – Jul 1
        { level: 'peak', from: 27, to: 34 }, // Jul 2 – Aug 26
        { level: 'uncertain', from: 35, to: 36 }, // Aug 27 – Sep 9
        { level: 'available', from: 37, to: 39 }, // Sep 10 – Sep 30
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Peaches',
      color: '#d5a479',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 21, to: 24 }, // May 21 – Jun 17
        { level: 'uncertain', from: 25, to: 27 }, // Jun 18 – Jul 8
        { level: 'peak', from: 28, to: 34 }, // Jul 9 – Aug 26
        { level: 'available', from: 35, to: 42 }, // Aug 27 – Oct 21
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Cantaloupes',
      color: '#d2a379',
      generated: true,
      default: false,
      spans: [
        { level: 'available', from: 28, to: 28 }, // Jul 9 – Jul 15
        { level: 'peak', from: 29, to: 36 }, // Jul 16 – Sep 9
        { level: 'uncertain', from: 37, to: 38 }, // Sep 10 – Sep 23
        { level: 'available', from: 39, to: 41 }, // Sep 24 – Oct 14
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Blackberries',
      color: '#3b3040',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 23, to: 28 }, // Jun 4 – Jul 15
        { level: 'uncertain', from: 29, to: 29 }, // Jul 16 – Jul 22
        { level: 'available', from: 30, to: 30 }, // Jul 23 – Jul 29
        { level: 'peak', from: 31, to: 37 }, // Jul 30 – Sep 16
        { level: 'available', from: 38, to: 41 }, // Sep 17 – Oct 14
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Grapes',
      color: '#765387',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 29, to: 30 }, // Jul 16 – Jul 29
        { level: 'peak', from: 31, to: 44 }, // Jul 30 – Nov 4
        { level: 'uncertain', from: 45, to: 45 }, // Nov 5 – Nov 11
        { level: 'available', from: 46, to: 49 }, // Nov 12 – Dec 9
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Pomegranates',
      color: '#88414a',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 38, to: 38 }, // Sep 17 – Sep 23
        { level: 'uncertain', from: 39, to: 39 }, // Sep 24 – Sep 30
        { level: 'peak', from: 40, to: 44 }, // Oct 1 – Nov 4
        { level: 'available', from: 45, to: 50 }, // Nov 5 – Dec 16
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Persimmons',
      color: '#b4693d',
      generated: true,
      default: true,
      spans: [
        { level: 'available', from: 44, to: 44 }, // Oct 29 – Nov 4
        { level: 'peak', from: 45, to: 49 }, // Nov 5 – Dec 9
        { level: 'available', from: 50, to: 51 }, // Dec 10 – Dec 23
      ],
      sources: [
        {
          credit:
            'USDA AMS Market News shipment volumes, 2019–2024 · Salinas-Watsonville, San Joaquin Valley, Central District',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
  ],
};
