// Generated by `bun run regions` — do not edit.
// Produce is defined in data/regions/, including hand-authored entries.
export default {
  id: 'sfbay',
  name: 'San Francisco Bay Area',
  schemaVersion: 1,
  items: [
    {
      name: 'Cherries',
      color: '#7a1f2b',
      generated: true,
      spans: [
        { level: 'available', from: 19, to: 20 }, // May 7 – May 20
        { level: 'peak', from: 21, to: 23 }, // May 21 – Jun 10
        { level: 'available', from: 24, to: 24 }, // Jun 11 – Jun 17
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/cherries.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Blueberries',
      color: '#4a6fa5',
      generated: true,
      spans: [
        { level: 'available', from: 18, to: 20 }, // Apr 30 – May 20
        { level: 'peak', from: 21, to: 24 }, // May 21 – Jun 17
        { level: 'available', from: 25, to: 26 }, // Jun 18 – Jul 1
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/blueberries.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Apricots',
      color: '#f0a83c',
      generated: true,
      spans: [
        { level: 'peak', from: 21, to: 21 }, // May 21 – May 27
        { level: 'available', from: 22, to: 22 }, // May 28 – Jun 3
        { level: 'peak', from: 23, to: 25 }, // Jun 4 – Jun 24
        { level: 'available', from: 26, to: 26 }, // Jun 25 – Jul 1
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/apricots.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Raspberries',
      color: '#c73e5a',
      generated: true,
      spans: [
        { level: 'available', from: 19, to: 23 }, // May 7 – Jun 10
        { level: 'peak', from: 24, to: 30 }, // Jun 11 – Jul 29
        { level: 'available', from: 31, to: 43 }, // Jul 30 – Oct 28
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/raspberries.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Strawberries',
      color: '#d1495b',
      generated: false,
      spans: [
        { level: 'available', from: 18, to: 22 }, // Apr 30 – Jun 3
        { level: 'peak', from: 23, to: 33 }, // Jun 4 – Aug 19
        { level: 'available', from: 34, to: 40 }, // Aug 20 – Oct 7
      ],
      sources: [
        {
          title:
            'The California Strawberry Industry: Current Trends and Future Prospects (2024), Fig. 5 — Salinas-Watsonville district weekly production volume, three-year average',
          url: 'https://www.tandfonline.com/doi/full/10.1080/15538362.2024.2342900',
        },
      ],
    },
    {
      name: 'Nectarines',
      color: '#e8703a',
      generated: true,
      spans: [
        { level: 'available', from: 21, to: 22 }, // May 21 – Jun 3
        { level: 'peak', from: 23, to: 33 }, // Jun 4 – Aug 19
        { level: 'available', from: 34, to: 38 }, // Aug 20 – Sep 23
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/nectarines.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Tomatoes',
      color: '#d1402f',
      generated: true,
      spans: [
        { level: 'available', from: 26, to: 28 }, // Jun 25 – Jul 15
        { level: 'peak', from: 29, to: 29 }, // Jul 16 – Jul 22
        { level: 'available', from: 30, to: 43 }, // Jul 23 – Oct 28
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — El Centro, CA Truck, Air and Boat Movement Report (EL_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/tomatoes.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Plums',
      color: '#8e3b5a',
      generated: true,
      spans: [
        { level: 'available', from: 23, to: 24 }, // Jun 4 – Jun 17
        { level: 'peak', from: 25, to: 34 }, // Jun 18 – Aug 26
        { level: 'available', from: 35, to: 41 }, // Aug 27 – Oct 14
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/plums.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Peaches',
      color: '#f2a25c',
      generated: true,
      spans: [
        { level: 'available', from: 21, to: 22 }, // May 21 – Jun 3
        { level: 'peak', from: 23, to: 25 }, // Jun 4 – Jun 24
        { level: 'available', from: 26, to: 26 }, // Jun 25 – Jul 1
        { level: 'peak', from: 27, to: 35 }, // Jul 2 – Sep 2
        { level: 'available', from: 36, to: 44 }, // Sep 3 – Nov 4
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/peaches.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Watermelons',
      color: '#e05c6e',
      generated: true,
      spans: [
        { level: 'available', from: 25, to: 26 }, // Jun 18 – Jul 1
        { level: 'peak', from: 27, to: 28 }, // Jul 2 – Jul 15
        { level: 'available', from: 29, to: 31 }, // Jul 16 – Aug 5
        { level: 'peak', from: 32, to: 35 }, // Aug 6 – Sep 2
        { level: 'available', from: 36, to: 40 }, // Sep 3 – Oct 7
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — El Centro, CA Truck, Air and Boat Movement Report (EL_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/watermelons.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Cantaloupes',
      color: '#eda15e',
      generated: true,
      spans: [
        { level: 'available', from: 21, to: 29 }, // May 21 – Jul 22
        { level: 'peak', from: 30, to: 30 }, // Jul 23 – Jul 29
        { level: 'available', from: 31, to: 31 }, // Jul 30 – Aug 5
        { level: 'peak', from: 32, to: 35 }, // Aug 6 – Sep 2
        { level: 'available', from: 36, to: 42 }, // Sep 3 – Oct 21
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — El Centro, CA Truck, Air and Boat Movement Report (EL_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/cantaloupes.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Blackberries',
      color: '#3d2b45',
      generated: true,
      spans: [
        { level: 'available', from: 21, to: 25 }, // May 21 – Jun 24
        { level: 'peak', from: 26, to: 27 }, // Jun 25 – Jul 8
        { level: 'available', from: 28, to: 30 }, // Jul 9 – Jul 29
        { level: 'peak', from: 31, to: 37 }, // Jul 30 – Sep 16
        { level: 'available', from: 38, to: 43 }, // Sep 17 – Oct 28
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/blackberries.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Grapes',
      color: '#7b4397',
      generated: true,
      spans: [
        { level: 'available', from: 28, to: 30 }, // Jul 9 – Jul 29
        { level: 'peak', from: 31, to: 43 }, // Jul 30 – Oct 28
        { level: 'available', from: 44, to: 51 }, // Oct 29 – Dec 23
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/grapes.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Pomegranates',
      color: '#9e2b3a',
      generated: true,
      spans: [
        { level: 'available', from: 38, to: 39 }, // Sep 17 – Sep 30
        { level: 'peak', from: 40, to: 40 }, // Oct 1 – Oct 7
        { level: 'available', from: 41, to: 49 }, // Oct 8 – Dec 9
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/pomegranates.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
    {
      name: 'Persimmons',
      color: '#d95f18',
      generated: true,
      spans: [
        { level: 'available', from: 43, to: 43 }, // Oct 22 – Oct 28
        { level: 'peak', from: 44, to: 46 }, // Oct 29 – Nov 18
        { level: 'available', from: 47, to: 47 }, // Nov 19 – Nov 25
        { level: 'peak', from: 48, to: 49 }, // Nov 26 – Dec 9
        { level: 'available', from: 50, to: 51 }, // Dec 10 – Dec 23
      ],
      sources: [
        {
          title:
            'USDA AMS Market News — Fresno, CA Truck, Air and Boat Movement Report (FR_FV170); California-grown, 2022–2024 seasons; season from weekly shipped weight (raw cache: data/raw/mars/ca/persimmons.jsonc)',
          url: 'https://www.ams.usda.gov/market-news/fruits-vegetables',
        },
      ],
    },
  ],
};
