// Generated by `bun run dependencies` — do not edit.
// What each one is for lives in src/lib/licenses.ts, which cannot be derived.

export interface ShippedDependency {
  name: string;
  version: string;
  license: string;
}

/** Every package that ships in the bundle, as resolved when this was last generated. */
export const SHIPPED: readonly ShippedDependency[] = [
  { name: 'd3-shape', version: '3.2.0', license: 'ISC' },
  { name: 'lucide-react', version: '1.25.0', license: 'ISC' },
  { name: 'markdown-to-jsx', version: '9.10.2', license: 'MIT' },
  { name: 'motion', version: '12.42.2', license: 'MIT' },
  { name: 'react', version: '19.2.7', license: 'MIT' },
  { name: 'react-dom', version: '19.2.7', license: 'MIT' },
  { name: 'react-router', version: '8.3.0', license: 'MIT' },
  { name: 'zod', version: '4.4.3', license: 'MIT' },
];
