import { type Level, peakMidpoint } from '@/src/lib/season';

export interface Span {
  level: Level;
  from: number;
  to: number;
}

export interface Source {
  credit: string;
  url: string | null;
}

/** A produce entry ready to write: derived from a source, or authored by hand. */
export interface Produce {
  name: string;
  color: string;
  generated: boolean;
  spans: Span[];
  sources: Source[];
}

/** What a source produces; `generated` is filled in by the renderer. */
export type GeneratedProduce = Omit<Produce, 'generated'>;

const MONTHS = 'Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec'.split(' ');

/** Approximate calendar date of a day-of-year, in a non-leap reference year. */
function dayLabel(dayOfYear: number): string {
  const date = new Date(Date.UTC(2025, 0, dayOfYear));
  return `${MONTHS[date.getUTCMonth()]} ${date.getUTCDate()}`;
}

/** Human-readable date range for a span, as an inline comment. */
function spanLabel(span: Span): string {
  return `${dayLabel((span.from - 1) * 7 + 1)} – ${dayLabel(span.to * 7)}`;
}

const quote = (value: string) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

function serializeProduce(produce: Produce): string {
  const spans = produce.spans
    .map((s) => `{ level: ${quote(s.level)}, from: ${s.from}, to: ${s.to} }, // ${spanLabel(s)}`)
    .join('\n');
  const sources = produce.sources
    .map((s) => `{ credit: ${quote(s.credit)}, url: ${s.url === null ? 'null' : quote(s.url)} },`)
    .join('\n');
  return [
    '{',
    `name: ${quote(produce.name)},`,
    `color: ${quote(produce.color)},`,
    `generated: ${produce.generated},`,
    'spans: [',
    spans,
    '],',
    'sources: [',
    sources,
    '],',
    '},',
  ].join('\n');
}

/**
 * Render a region's data module.
 *
 * The whole file is generated, so there is nothing hand-authored to preserve and no merging
 * to do — hand-authored produce lives in the region's crop list instead, and arrives here as
 * ordinary entries. Items come out sorted by peak midpoint, which is the order the schema
 * requires and the diagonal the poster reads along.
 *
 * Output is piped through the formatter so this function alone decides the bytes on disk;
 * the test that checks the committed files compares against exactly this.
 */
export async function renderRegionFile(
  region: { id: string; name: string },
  produce: Produce[],
): Promise<string> {
  const items = [...produce].sort((a, b) => peakMidpoint(a.spans) - peakMidpoint(b.spans));
  const source = [
    '// Generated by `bun run regions` — do not edit.',
    '// Produce is defined in data/regions/, including hand-authored entries.',
    'export default {',
    `id: ${quote(region.id)},`,
    `name: ${quote(region.name)},`,
    'schemaVersion: 1,',
    'items: [',
    items.map(serializeProduce).join('\n'),
    '],',
    '};',
  ].join('\n');

  return new Response(
    Bun.spawn(['bunx', 'oxfmt', '--stdin-filepath', 'region.ts'], {
      stdin: new TextEncoder().encode(source),
      stdout: 'pipe',
    }).stdout,
  ).text();
}
