import { readFileSync } from 'node:fs';

/**
 * Regenerate the shipped-dependency list for the licences page.
 *
 *   bun run dependencies
 *
 * Name, version and licence all exist already — in package.json and in each package's own
 * manifest — so transcribing them by hand is a second copy that goes stale silently, and a
 * licences page that is quietly wrong is worse than none. What cannot be derived is what each
 * library is *for*; that stays hand-written in src/lib/licenses.ts and is joined on at runtime.
 *
 * Only `dependencies` are listed. Dev tools never reach a reader's browser, so their notices are
 * not ours to pass on.
 *
 * tests/generatedDependencies.test.ts regenerates and compares byte for byte, so a dependency
 * added without rerunning this fails CI.
 */
export const OUTPUT = 'src/lib/__generated__/dependencies.ts';

interface Manifest {
  version?: string;
  license?: string;
}

export function renderDependencies(): Promise<string> {
  const root = JSON.parse(readFileSync('package.json', 'utf8')) as {
    dependencies?: Record<string, string>;
  };
  const names = Object.keys(root.dependencies ?? {}).sort();

  const rows = names.map((name) => {
    const manifest = JSON.parse(
      readFileSync(`node_modules/${name}/package.json`, 'utf8'),
    ) as Manifest;
    if (!manifest.version || !manifest.license) {
      throw new Error(`${name}: no version or license in its manifest`);
    }
    return `{ name: '${name}', version: '${manifest.version}', license: '${manifest.license}' },`;
  });

  const source = [
    '// Generated by `bun run dependencies` — do not edit.',
    '// What each one is for lives in src/lib/licenses.ts, which cannot be derived.',
    '',
    'export interface ShippedDependency {',
    'name: string;',
    'version: string;',
    'license: string;',
    '}',
    '',
    '/** Every package that ships in the bundle, as resolved when this was last generated. */',
    'export const SHIPPED: readonly ShippedDependency[] = [',
    ...rows,
    '];',
  ].join('\n');

  return new Response(
    Bun.spawn(['bunx', 'oxfmt', '--stdin-filepath', 'dependencies.ts'], {
      stdin: new TextEncoder().encode(source),
      stdout: 'pipe',
    }).stdout,
  ).text();
}

if (import.meta.main) {
  await Bun.write(OUTPUT, await renderDependencies());
  console.log(`wrote ${OUTPUT}`);
}
